### ISSUE TITLE
Reported 500 error loop

### ISSUE THREAD

**Issue by chasecmiller** [chasecmiller/Crumbls-Cache#2]
@mxmkmarquette reports a 500 error with object-cache using memcache/memcached.

Hoping to get log from latest version, otherwise auto-closing issue in 7 days.

**Comment by mxmkmarquette** [comment]
it's working as it should no more the loop bug.

**Comment by chasecmiller** [comment]
Great, thanks!

**Comment by chasecmiller** [comment]
Only system supported cache types will now show up in the list.  That should make testing easier.
