### ISSUE TITLE
Group use in wordpress

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#20]
transient
options
users
user_meta
userlogins
counts
posts
post_meta
themes
comment
site-transient
site-options
non-persistent

this is the group use in wordpress maybe we can tweak the caching options

like habitually transient and site-transient are cache together, maybe try it and or offers an options to add some other groupe to the transient group. 

or rename it something else or add a new section called specific cache an option that will make you decide what you want to cache with what group....

**Comment by mxmkmarquette** [comment]
like we can do maybe 6 category

themes that will cache:
themes
options
site-options

users that will cache:
users
user_meta
userlogins

posts that will cache:
counts
posts
post_meta

transient that will cache:
site-transient
transient

comment that will cache:
comment

and lastly non-persistent that will cache:
non-persistent

drop down menu to choose what type of cache will cache what group.

**Comment by chasecmiller** [comment]
Personally, I feel like this might be a bit of overkill.  A lot of these just have overlap and would actually slow down the current functionality.  The majority of it is naturally handled by object caching.  Is there any reason to actually do this?

**Comment by mxmkmarquette** [comment]
just to be more efficient but if you think it's not let's not do this. :) and i'm making fastcomet installing almost all drivers we need so we will be able to test more caching option.

**Comment by chasecmiller** [comment]
For right now, I think it is extreme overkill.  If the environment ever changes enough, there is a pull request that handles it, or enough push if anyone ever uses this plugin, then I'll write it in.

Good idea!
