### ISSUE TITLE
after installing last push

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#23]
`> Fatal error: Uncaught phpFastCache\Exceptions\phpFastCacheDriverException: PLEASE CREATE OR CHMOD /var/www/html/crumbls/wp-content/cache/crumbls/madmax.quebec/Files - 0777 OR ANY WRITABLE PERMISSION! in /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php:105 Stack trace: #0 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php(141): phpFastCache\Drivers\Files\Driver->getPath() #1 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(71): phpFastCache\Drivers\Files\Driver->getFileDir() #2 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Drivers/Files/Driver.php(61): phpFastCache\Drivers\Files\Driver->driverCheck() #3 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Ca in /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/Core/PathSeekerTrait.php on line 105`

**Comment by mxmkmarquette** [comment]
if you want to take a look i rename crumbls_cache to crumbls_cache-disabled and remove advanced-cache.php et object-cache.php

**Comment by chasecmiller** [comment]
I'll look at it here in about 10 minutes.  It sounds like your file path is invalid.

**Comment by chasecmiller** [comment]
Erase your config.php file so it regenerates.  I am adding config.php to gitignore.  It overwrote your settings.

**Comment by mxmkmarquette** [comment]
done work correctly now but into the admin interface i got this.

`Fatal error: Uncaught Error: Class 'phpFastCache\Drivers\Elasticache\Driver' not found in /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/CacheManager.php:107 Stack trace: #0 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/admin.php(111): phpFastCache\CacheManager::getInstance('Elasticache', Array) #1 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/admin.php(176): crumbls\plugins\fastcache\Admin->getSupported() #2 /home/madmax/public_html/wp-includes/class-wp-hook.php(298): crumbls\plugins\fastcache\Admin->pageCache('') #3 /home/madmax/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #4 /home/madmax/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /home/madmax/public_html/wp-admin/admin.php(222): do_action('settings_page_c...') #6 {main} thrown in /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpfastcache/src/phpFastCache/CacheManager.php on line 107`

**Comment by chasecmiller** [comment]
Did you do a full update?  Sounds like you don't see the elasticache driver now.

**Comment by mxmkmarquette** [comment]
let me redo it and i'm gonna tell you.

**Comment by mxmkmarquette** [comment]
same problem

**Comment by chasecmiller** [comment]
Gonna log in and check.   It comes with the elasticache driver.  I added it last night.

**Comment by mxmkmarquette** [comment]
perfect no problemo my friend  and thank you again.

**Comment by chasecmiller** [comment]
Ah, looks like it got uploaded to the wrong directory.  Not sure if that was you or me.  Working through an update with a quick fix in it to handle another issue that was throwing a 500 on your server.

**Comment by chasecmiller** [comment]
Wrapped that up.  It was all due to files being copied to the wrong location.  I updated the plugin on your end and removed config.php from the git.
