### ISSUE TITLE
not showing that item is cache in source code.

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#27]
when i open a private windows it's not showing like Cache => randommd5 number. in the source code.

**Comment by chasecmiller** [comment]
Your server is running a library that trims the tailing comments off.  It's most likely a compression library.  For example, you can see it tailing http://crumbls.com

**Comment by mxmkmarquette** [comment]
yeah that's true so sorry for this one my friend.
