### ISSUE TITLE
issue with last push

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#28]
Got that on top of the files in the admin:

`Array ( [0] => stdClass Object ( [no] => 1024 [str] => A Symfony Bundle To Make The PhpFastCache Integration More Easier Is Now Available Here Https github com PHPSocialNetwork phpfastcache bundle [file] => /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpFastCache/CacheManager.php [line] => 103 ) [1] => stdClass Object ( [no] => 1024 [str] => A Symfony Bundle To Make The PhpFastCache Integration More Easier Is Now Available Here Https github com PHPSocialNetwork phpfastcache bundle [file] => /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpFastCache/CacheManager.php [line] => 103 ) [2] => stdClass Object ( [no] => 1024 [str] => A Symfony Bundle To Make The PhpFastCache Integration More Easier Is Now Available Here Https github com PHPSocialNetwork phpfastcache bundle [file] => /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/assets/php/phpFastCache/CacheManager.php [line] => 103 ) )`

**Comment by chasecmiller** [comment]
Looks like ignoreSymfonyNotice was configured to false, most likely in yoru config.php file.  I am going to put a force ignore out for this.
