### ISSUE TITLE
issue with last push not able to access my home page

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#30]
i'm able to install it, all error have been push away but now i'm not able to access the home page of my wordpress it's telling me this error

`[19-Apr-2017 20:13:29 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_normalize_path() in /home/madmax/public_html/wp-includes/plugin.php:645
Stack trace:
#0 /home/madmax/public_html/wp-includes/plugin.php(746): plugin_basename('/home/madmax/pu...')
#1 /home/madmax/public_html/neufsvies/wp-content/plugins/crumbls_cache/plugin.php(1040): register_activation_hook('/home/madmax/pu...', Array)
#2 /home/madmax/public_html/neufsvies/wp-content/advanced-cache.php(19): require_once('/home/madmax/pu...')
#3 /home/madmax/public_html/wp-settings.php(84): include('/home/madmax/pu...')
#4 /home/madmax/public_html/wp-config.php(129): require_once('/home/madmax/pu...')
#5 /home/madmax/public_html/wp-load.php(37): require_once('/home/madmax/pu...')
#6 /home/madmax/public_html/wp-blog-header.php(13): require_once('/home/madmax/pu...')
#7 /home/madmax/public_html/index.php(17): require('/home/madmax/pu...')
#8 {main}
  thrown in /home/madmax/public_html/wp-includes/plugin.php on line 645`

like i can go in every admin page but madmax.quebec error 500

**Comment by chasecmiller** [comment]
If you do a return before the register_activation_hook, it will block that. Trying to work out the register, etc functions.

**Comment by mxmkmarquette** [comment]
yep it fixing it :)
