### ISSUE TITLE
i install the plugin on an other website

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#34]
a little website that i'm launching and i got this

qc-me.me the index page is messup but section are okay...

**Comment by chasecmiller** [comment]
I need more details to try and troubleshoot.

**Comment by mxmkmarquette** [comment]
i download the version from madmax and i install it on qc-me.me it like it use temporary the cache of madmax then i change the elasticache to other server and else but the home/front page is buggy like.

http://qc-me.me/ <-- this is buddy not able to retrive files but this http://qc-me.me/l23jd is okay 

on your side is it okay or it's just on my hand like

**Comment by mxmkmarquette** [comment]
it's now okay was a bug with browser cache.
