### ISSUE TITLE
make the option of minify the html a comeback

### ISSUE THREAD

**Issue by mxmkmarquette** [chasecmiller/Crumbls-Cache#38]
seriously it was working real nice and smoothly, i don't know if it's working and the option is just not there like hide, but it was a real real real nice feature.

**Comment by chasecmiller** [comment]
Do you mean a callback?  I'm going to take 3 days off from the project to work on another task, but want to look at this first.

**Comment by mxmkmarquette** [comment]
prior this version and like between some version we had the option to hit a box with the option to minify or not the html but in this version it seem gone.
