### ISSUE TITLE
Implementation: APCU

### ISSUE THREAD

**Issue by chasecmiller** [chasecmiller/Crumbls-Cache#4]
Bring APCU online.

**Comment by chasecmiller** [comment]
Unable to test.  Dev env is only php7 and apcu is not supported yet.  Looking for help testing.

**Comment by mxmkmarquette** [comment]
i think we can test apcu on my hosting i have it if i remember

**Comment by mxmkmarquette** [comment]
http://madmax.quebec/info.php it seems that apcu is installed on my server.

**Comment by chasecmiller** [comment]
Sounds good.  

Before we upgrade, let me write the clear cache buttons back in.  I'll do it after I take a quick lunch.

**Comment by mxmkmarquette** [comment]
no problemo my friend bonne appetit !!!
